package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	os.Setenv("FOO", "1")
	fmt.Println("FOO", os.Getenv("KOO"))
	fmt.Println("BAR", os.Getenv("BAR"))
	fmt.Println()

	for _, e := range os.Environ() {
		n := strings.SplitN(e, "=", 2)
		fmt.Println(n[0])
	}
}

//FOO
//BAR
//
//FOO
//USERDOMAIN_ROAMINGPROFILE
//PROCESSOR_LEVEL
//SESSIONNAME
//ALLUSERSPROFILE
//PROCESSOR_ARCHITECTURE
//GATEWAY_VM_OPTIONS
//PSModulePath
//SystemDrive
//RIDER_VM_OPTIONS
//USERNAME
//DEVECOSTUDIO_VM_OPTIONS
//STUDIO_VM_OPTIONS
//ProgramFiles(x86)
//FPS_BROWSER_USER_PROFILE_STRING
//PATHEXT
//APPCODE_VM_OPTIONS
//DriverData
//GOPATH
//ProgramData
//DATASPELL_VM_OPTIONS
//ProgramW6432
//HOMEPATH
//PROCESSOR_IDENTIFIER
//ProgramFiles
//PUBLIC
//windir
//
//ZES_ENABLE_SYSMAN
//DATAGRIP_VM_OPTIONS
//LOCALAPPDATA
//USERDOMAIN
//WEBSTORM_VM_OPTIONS
//LOGONSERVER
//PYCHARM_VM_OPTIONS
//FPS_BROWSER_APP_PROFILE_STRING
//CLION_VM_OPTIONS
//JETBRAINSCLIENT_VM_OPTIONS
//GOLAND_VM_OPTIONS
//OneDrive
//APPDATA
//IDEA_VM_OPTIONS
//RUBYMINE_VM_OPTIONS
//JETBRAINS_CLIENT_VM_OPTIONS
//VBOX_MSI_INSTALL_PATH
//CommonProgramFiles
//Path
//OS
//COMPUTERNAME
//EFC_21680
//PROCESSOR_REVISION
//GOROOT
//CommonProgramW6432
//ComSpec
//GO111MODULE
//
//TEMP
//SystemRoot
//WEBIDE_VM_OPTIONS
//HOMEDRIVE
//USERPROFILE
//TMP
//CommonProgramFiles(x86)
//NUMBER_OF_PROCESSORS
//PHPSTORM_VM_OPTIONS
//IDEA_INITIAL_DIRECTORY
